优化 - 去除编译警告 - service内容优化 - 解决wiringpi导致的编译出错问题

diff --git a/rpi-lcd b/rpi-lcd
--- a/rpi-lcd
+++ b/rpi-lcd
@@ -211,6 +211,11 @@ remove() {
 }
 
 
+if [[ $EUID -ne 0 ]]; then
+    echo -e "\n\tError:This script must be run as root!\n" 
+    exit 1
+fi
+
 FUNCTION_NAME=$2
 ARGUMENT=$3
 $FUNCTION_NAME $ARGUMENT
